name: protos
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  grpc: 3.1.0
  protobuf:
  logging:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
# dependencies: {grpc: ^3.1.0, protobuf: ^2.1.0}
